### ISSUE TITLE
NVIDIA-Driver - blank screen after running install.sh

### ISSUE THREAD

**Issue by epifanio** [lebensterben/awesome-clear-linux#17] opened 2021-06-04 20:26 UTC
Attemting to install the NVIDIA Driver on my system - I got a blank screen after tunning [install.sh](https://github.com/lebensterben/awesome-clear-linux/blob/master/NVIDIA-Driver/install.bash)

Note: Before trying this repository scripts I first tried to follow the directions on:  https://docs.01.org/clearlinux/latest/tutorials/nvidia.html step-by-step .. and I got the same results. At this point of failure I am not even able to boot into txt mode .. as my 60% keyboard seems to not be able to send ctrl+alt+Fx .. to login into a shell.

Do you have any idea how to debug the issue? I am running this on an AMD R9 system if that is important. My next attempt will be to try to log in via ssh and see what is going on, but that will require a re-installation of the entire system for the third time ..

**Comment by lebensterben** [comment] 2021-06-04 20:37
are you on a laptop? you must disable integrated GPU in BIOS.

**Comment by epifanio** [comment] 2021-06-04 20:55
This is on a Desktop, Ryzen 9 5950X - NVIDIA GTX 1070 - Modo Asus CrossHair VIII wifi
Virtualization is ON, as I was using it .. but I can try to disable it if needed.

**Comment by epifanio** [comment] 2021-06-04 21:34
quick update:
I did a chroot log-in from the installation disk to running the uninstall script first and then the clean-up ..  so I was able to restore the Open Source drivers.  I am back able to log in. 
Before uninstalling I first tried to run the post-install script, which failed as no Nvidia modules were found (to confirm the installation process failed)

**Comment by lebensterben** [comment] 2021-06-04 21:41
the tutorial is intended to work with iGPU+NVIDIA GPU. And the scripts are based on the tutorial.

To work with AMD, changes need to be made so that its integrated GPU is disabled.

**Comment by epifanio** [comment] 2021-06-05 04:26
I see, I also tried a different distro, and seems there are some issues related to new kernels and Nvidia drivers - with ubuntu I even managed to have a kernel panic after installing the driver (465, from nvidia-detect) -  there is no iGPU on the 5950x, I can try a clean driver installation using older version ... to see if something changes. Thanks!

**Comment by lebensterben** [comment] 2021-06-05 05:45
of course you don't have iGPU, that's for Intel.

since this is not a bug, I'm closing this issue.

**Closed by lebensterben** 2021-06-05 05:45 UTC
